M48
; DRILL file {KiCad 8.0.4} date 2024-10-26T11:38:53+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-26T11:38:53+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X93.941Y-143.471
X95.211Y-95.211
X146.011Y-110.451
X146.011Y-138.391
M30
